ALTER TABLE dbo.Product ALTER COLUMN Name NVARCHAR(200) NOT NULL;
ALTER TABLE dbo.Product ALTER COLUMN MetaKeywords NVARCHAR(200) NULL;
ALTER TABLE dbo.Product ALTER COLUMN MetaTitle NVARCHAR(200) NULL;
ALTER TABLE dbo.Product ALTER COLUMN Sku NVARCHAR(200) NULL;
ALTER TABLE dbo.Product ALTER COLUMN ManufacturerPartNumber NVARCHAR(200) NULL;
ALTER TABLE dbo.Product ALTER COLUMN Gtin NVARCHAR(200) NULL;
ALTER TABLE dbo.Product ALTER COLUMN RequiredProductIds NVARCHAR(200) NULL;
ALTER TABLE dbo.Product ALTER COLUMN AllowedQuantities NVARCHAR(200) NULL;
IF COL_LENGTH('dbo.Product','StockStatus') IS NULL ALTER TABLE dbo.Product Add StockStatus char(1) NULL